CREATE TABLE "especies" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_tecnico" varchar,
  "nombre_comun" varchar,
  "caracteristicas" text,
  "instrucciones_cuidado" text,
  "creado_at" timestamp
);

CREATE TABLE "lotes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "especie_id" int NOT NULL,
  "fecha_siembra" date,
  "cantidad_inicial" int,
  "cantidad_actual" int,
  "estado" varchar,
  "ubicacion" varchar,
  "creado_at" timestamp
);

CREATE TABLE "movimientos_inventario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipo" varchar,
  "referencia_id" int,
  "usuario_id" int,
  "fecha_movimiento" timestamp,
  "notas" text
);

CREATE TABLE "detalles_movimiento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movimiento_id" int NOT NULL,
  "lote_id" int NOT NULL,
  "cantidad" int,
  "tipo_operacion" varchar
);

CREATE TABLE "ventas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cliente_id" int,
  "total" decimal,
  "metodo_pago" varchar,
  "fecha_venta" timestamp
);

CREATE TABLE "detalles_venta" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "venta_id" int NOT NULL,
  "lote_id" int NOT NULL,
  "cantidad" int,
  "precio_unitario" decimal
);

CREATE TABLE "proyectos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "tipo" varchar,
  "estado" varchar,
  "fecha_inicio" date,
  "fecha_fin" date
);

CREATE TABLE "reservas_lote" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lote_id" int NOT NULL,
  "proyecto_id" int NOT NULL,
  "cantidad_reservada" int,
  "fecha_reserva" timestamp,
  "fecha_vencimiento" timestamp,
  "estado" varchar
);

CREATE TABLE "insumos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "tipo" varchar,
  "unidad" varchar
);

CREATE TABLE "entradas_insumos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "insumo_id" int NOT NULL,
  "cantidad" decimal,
  "costo_total" decimal,
  "proveedor_id" int,
  "fecha_entrada" timestamp
);

CREATE TABLE "costos_produccion" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lote_id" int NOT NULL,
  "costo_total" decimal,
  "costo_unitario" decimal,
  "fecha_calculo" timestamp
);

CREATE TABLE "trabajadores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "cedula" varchar,
  "telefono" varchar
);

CREATE TABLE "tareas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "tipo" varchar,
  "fecha_programada" date,
  "duracion_horas" int,
  "estado" varchar
);

CREATE TABLE "asignaciones_tarea" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "trabajador_id" int NOT NULL,
  "tarea_id" int NOT NULL
);

CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre_usuario" varchar,
  "contrasena" varchar,
  "rol_id" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "clientes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "informacion_contacto" varchar
);

CREATE TABLE "proveedores" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "tipo" varchar,
  "informacion_contacto" varchar
);

ALTER TABLE "lotes" ADD FOREIGN KEY ("especie_id") REFERENCES "especies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalles_movimiento" ADD FOREIGN KEY ("movimiento_id") REFERENCES "movimientos_inventario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalles_movimiento" ADD FOREIGN KEY ("lote_id") REFERENCES "lotes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalles_venta" ADD FOREIGN KEY ("venta_id") REFERENCES "ventas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "detalles_venta" ADD FOREIGN KEY ("lote_id") REFERENCES "lotes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ventas" ADD FOREIGN KEY ("cliente_id") REFERENCES "clientes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservas_lote" ADD FOREIGN KEY ("lote_id") REFERENCES "lotes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "reservas_lote" ADD FOREIGN KEY ("proyecto_id") REFERENCES "proyectos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entradas_insumos" ADD FOREIGN KEY ("insumo_id") REFERENCES "insumos" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "entradas_insumos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "proveedores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "costos_produccion" ADD FOREIGN KEY ("lote_id") REFERENCES "lotes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asignaciones_tarea" ADD FOREIGN KEY ("trabajador_id") REFERENCES "trabajadores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "asignaciones_tarea" ADD FOREIGN KEY ("tarea_id") REFERENCES "tareas" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
