CREATE TABLE "species" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "technical_name" varchar,
  "common_name" varchar,
  "characteristics" text,
  "care_instructions" text,
  "created_at" timestamp
);

CREATE TABLE "lots" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "species_id" int NOT NULL,
  "sowing_date" date,
  "initial_quantity" int,
  "current_quantity" int,
  "status" varchar,
  "location" varchar,
  "created_at" timestamp
);

CREATE TABLE "inventory_movements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar,
  "reference_id" int,
  "user_id" int,
  "movement_date" timestamp,
  "notes" text
);

CREATE TABLE "movement_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "movement_id" int NOT NULL,
  "lot_id" int NOT NULL,
  "quantity" int,
  "operation_type" varchar
);

CREATE TABLE "sales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "total" decimal,
  "payment_method" varchar,
  "sale_date" timestamp
);

CREATE TABLE "sale_details" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sale_id" int NOT NULL,
  "lot_id" int NOT NULL,
  "quantity" int,
  "unit_price" decimal
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "status" varchar,
  "start_date" date,
  "end_date" date
);

CREATE TABLE "lot_reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lot_id" int NOT NULL,
  "project_id" int NOT NULL,
  "reserved_quantity" int,
  "reservation_date" timestamp,
  "expiration_date" timestamp,
  "status" varchar
);

CREATE TABLE "inputs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "unit" varchar
);

CREATE TABLE "input_entries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "input_id" int NOT NULL,
  "quantity" decimal,
  "total_cost" decimal,
  "supplier_id" int,
  "entry_date" timestamp
);

CREATE TABLE "production_costs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lot_id" int NOT NULL,
  "total_cost" decimal,
  "unit_cost" decimal,
  "calculation_date" timestamp
);

CREATE TABLE "workers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "dni" varchar,
  "phone" varchar
);

CREATE TABLE "tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "scheduled_date" date,
  "duration_hours" int,
  "status" varchar
);

CREATE TABLE "task_assignments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "worker_id" int NOT NULL,
  "task_id" int NOT NULL
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "password" varchar,
  "role_id" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "clients" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "contact_info" varchar
);

CREATE TABLE "suppliers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "contact_info" varchar
);

ALTER TABLE "lots" ADD FOREIGN KEY ("species_id") REFERENCES "species" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movement_details" ADD FOREIGN KEY ("movement_id") REFERENCES "inventory_movements" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "movement_details" ADD FOREIGN KEY ("lot_id") REFERENCES "lots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_details" ADD FOREIGN KEY ("sale_id") REFERENCES "sales" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale_details" ADD FOREIGN KEY ("lot_id") REFERENCES "lots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lot_reservations" ADD FOREIGN KEY ("lot_id") REFERENCES "lots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lot_reservations" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "input_entries" ADD FOREIGN KEY ("input_id") REFERENCES "inputs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "input_entries" ADD FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "production_costs" ADD FOREIGN KEY ("lot_id") REFERENCES "lots" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "task_assignments" ADD FOREIGN KEY ("worker_id") REFERENCES "workers" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "task_assignments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;
